# Generated by Django 2.1.7 on 2019-03-12 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('lest_name', models.CharField(max_length=30)),
                ('adderss', models.CharField(max_length=330)),
                ('date_birth', models.DateField()),
                ('death_birth', models.CharField(default='more n', help_text='yeare-menth-day', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=121)),
                ('summary', models.TextField(help_text='Enter briet deseription of The Book', max_length=1000)),
                ('publisher', models.CharField(max_length=111)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='second.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(help_text='Enter your book name ....', max_length=222)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='pub_name',
            field=models.ManyToManyField(help_text='Select a Book', to='second.Name'),
        ),
    ]
